In [1]:
import numpy as np

#Problem 1a

C = np.array([6, -4, 27])

C

array([ 6, -4, 27])

In [2]:
#Problem 1b

C = C.reshape((3,1))

C

array([[ 6],
       [-4],
       [27]])

In [3]:
#Problem 1c

C[2,0]

27

In [4]:
#Problem 1d

C[1:,0]

array([-4, 27])

In [5]:
#Problem 1e

C[-2:,0]

array([-4, 27])

In [6]:
#Problem 1f

A = np.array([[1,1,1],[0,2,5],[2,5,-1]])

A

array([[ 1,  1,  1],
       [ 0,  2,  5],
       [ 2,  5, -1]])

In [7]:
#Problem 1g

A[1,2]

5

In [8]:
#Problem 1h

A[2,:]

array([ 2,  5, -1])

In [9]:
#Problem 1i

A[:,-1]

array([ 1,  5, -1])

In [10]:
#Problem 1j

from numpy.linalg import det

det(A)

#non singular

-21.0

**Problem 1k**

$ x_1 + x_2 + x_3 = 6 $

$ 2x_2 + 5x_3 = -4 $

$ 2x_1 + 5x_2 - x_3 = 27 $

In [11]:
#Problem 1l

from numpy.linalg import inv

x = inv(A) @ C

x

array([[ 5.],
       [ 3.],
       [-2.]])

In [12]:
#Problem 1m

A[0,:].reshape(1,3) @ x

array([[6.]])

In [13]:
#Problem 1n

A @ x

array([[ 6.],
       [-4.],
       [27.]])

In [14]:
#Problem 1p

x_transpose = x.T

x_transpose @ A

array([[ 1.,  1., 22.]])

In [15]:
#Problem 1q

eigenvalues, eigenvectors = np.linalg.eig(A)

eigenvalues

array([-4.77879032,  0.72601723,  6.05277309])

**Problem 2.1**

Rise. 10-year yield went from 5% to 8.5% and since it's the average expected return of 10 1-year bonds that means in order for the average to be higher the short-term interest rates have to rise relative to the expected values from year 1.

**Problem 2.2**

Decreased.