# Vector

- Vector of length n is a sequence of numbers, written as x = $(x_1,...x_n)$ or x = $[x_1,...x_n]$

- A 1-by-n vector is a horizontal vector and an n-by-1 vector is a vertical vector

- n-by-m is an n row, m column matrix

In [1]:
import numpy as np

x_1d = np.array([1,2,3])

x_1d

array([1, 2, 3])

In [3]:
x_1d.shape

(3,)

In [8]:
y_1d = x_1d.reshape((3,1))

y_1d

[[1]
 [2]
 [3]]


In [9]:
y_1d.shape

(3, 1)


In [10]:
z_1d = x_1d.reshape((1,3))

z_1d

array([[1, 2, 3]])

In [11]:
z_1d.shape

(1, 3)

# Vector Operations

- Addition + Subtraction (of same shape)
- Scalar multiplication


In [12]:
x_1d+z_1d

array([[2, 4, 6]])

In [13]:
x_1d-z_1d

array([[0, 0, 0]])

In [14]:
3*x_1d

array([3, 6, 9])

In [15]:
x_1d/3

array([0.33333333, 0.66666667, 1.        ])

# Transpose

Denoted: x' or $x^T$
- x = $[x_1,...,x_n]$
- $x^T$ = vertical vector $[x_1,...,x_n]$


In [16]:
y_1d.T

array([[1, 2, 3]])

# Dot Product

x • y = horizontal • vertical = $x_1•y_1 \;+\; ... \;+ \;x_n•y_n$ = **integer k**

In [23]:
z_1d @ y_1d #dot product

array([[14]])

In [21]:
z_1d.shape #horizontal

(1, 3)

In [22]:
y_1d.shape #vertical

(3, 1)

# Element-wise operations

not math, just python specific operations

In [24]:
z_1d * x_1d

array([[1, 4, 9]])

In [25]:
z_1d / x_1d

array([[1., 1., 1.]])

In [26]:
x_1d + 3

array([4, 5, 6])

# Creating arrays

In [28]:
ls = [0.5, 0.25, 3]
x = np.array([ls])

In [29]:
x

array([[0.5 , 0.25, 3.  ]])

In [34]:
a = np.zeros(5) #default float

In [31]:
a

array([0., 0., 0., 0., 0.])

In [36]:
a = np.zeros(3,dtype=int)

In [37]:
a

array([0, 0, 0])

In [38]:
type(a[1])

numpy.int64

In [39]:
b = np.ones(5)

In [40]:
b

array([1., 1., 1., 1., 1.])

In [41]:
c = np.empty(6)

In [42]:
c

array([0.e+000, 3.e-323, 0.e+000, 0.e+000, 0.e+000, 0.e+000])

# Exercise

Task: re-write the get_PV function using dot product

In [62]:
def get_PV(FP,i,n):
    total = 0
    for j in range(n):
        total = total + FP/(i+1)**(j+1)
    return total

In [63]:
get_PV(126,.1,25)

1143.7070422968989

In [104]:
def get_PV2(FP,i,n):
    hor_ls = [FP/(1+i)**(t+1) for t in range(n)]
    
    x_arr = np.array(hor_ls)
    x_arr = x_arr.reshape(1,n)
    
    y_arr = np.ones(n)
    y_arr = y_arr.reshape(n,1)
    
    return x_arr @ y_arr

get_PV2(126,.1,25)

array([[1143.7070423]])

# Matrices

- An n-by-k (or n x k) matrix is a rectangular array A of numbers with n rows and k columns
- An n x n matrix is a square matrix
- A diagonal matrix is a matrix with 0s everywhere except the diagonal

In [81]:
my_list = [[1,2,3], [4,5,6], [7,8,9]]

x_2d = np.array(my_list)

In [82]:
x_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [83]:
x_2d.shape

(3, 3)

In [89]:
x_2d[1,1]

5

In [90]:
x_2d[1,:]

array([4, 5, 6])

In [91]:
x_2d[:,2]

array([3, 6, 9])

# Exercise

Find 2nd and 3rd elements in second row

In [95]:
x_2d[1,1:3]

array([5, 6])

In [96]:
x_2d.reshape(1,9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [99]:
x_2d.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [105]:
x_2d = x_2d.reshape(1,9)

In [106]:
rows, columns = x_2d.shape