# Matrices

- n-by-m matrix has n rows and m columns

In [1]:
import numpy as np

# Matrix Operations

In [2]:
z = np.empty((3,3))

In [3]:
z

array([[ 6.17779239e-31, -1.23555848e-30,  3.08889620e-31],
       [-1.23555848e-30,  2.68733969e-30, -8.34001973e-31],
       [ 3.08889620e-31, -8.34001973e-31,  4.78778910e-31]])

In [4]:
z[0,0]

6.177792392231797e-31

In [5]:
x = np.array([])

In [6]:
x

array([], dtype=float64)

In [7]:
x.shape

(0,)

In [8]:
z[:] = 3

In [9]:
z

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [10]:
z = np.zeros((4,3))

In [11]:
z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
z.shape

(4, 3)

In [13]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

**Identity matrix**: diagonal matrix with 1's on the diagonal

In [14]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Transpose

denoted $M^T$ is M with columns as rows and rows as columns

In [22]:
A = np.array([[2,4,6],[3,4,7]])

In [23]:
A

array([[2, 4, 6],
       [3, 4, 7]])

In [21]:
A.T

array([[2, 3],
       [4, 5],
       [6, 7]])

In [24]:
B = np.array([3.5,5,19]).reshape((3,1))

In [26]:
B

array([[ 3.5],
       [ 5. ],
       [19. ]])

In [27]:
A @ B

array([[141. ],
       [163.5]])

# Exercise

Create a matrix and a vector. Try the product of them.

In [29]:
A_ls = [[1,2],[3,4],[5,6]]
A = np.array(A_ls)

b_ls = [[1,2]]
b = np.array(b_ls).reshape((2,1))

A @ B

array([[ 5],
       [11],
       [17]])

# Matrix multiplication

**n-by-k** and **n-by-m** yields **n-by-m**

# Exercise

In [31]:
A = np.array([[2,1],[1,1]])
B = np.array([[1,-1],[0,2]])

A @ B

array([[2, 0],
       [1, 1]])

In [32]:
B @ A

array([[1, 0],
       [2, 2]])

# Matrix Axioms

- Associative (Addition)
- Commutative (Addition)
- Associative (Multiplication)
- Distributive (Addition)


In [33]:
A

array([[2, 1],
       [1, 1]])

In [34]:
A @ np.eye(2)

array([[2., 1.],
       [1., 1.]])

# Inverse

Matrix must be a square to have an inverse

$A*A^{-1}$ = $A^{-1}A$ := **I**

A square matrix can only be inverted if its **determinant** is **NOT** 0

If determinant is equal to 0, we say the matrix is **singular** -> *columns* are related

In [38]:
A_inverse = np.linalg.inv(A)

In [39]:
A @ A_inverse

array([[1., 0.],
       [0., 1.]])

In [44]:
from numpy.linalg import inv

A_inverse = inv(A)

In [45]:
from numpy.linalg import det

det(A)

1.0

In [46]:
A = np.array([[3,8],[4,11]])
B = np.array([5,7]).reshape((2,1))

inv(A) @ B

array([[-1.],
       [ 1.]])

# Eigenvalue

An **eigenvalue** of a square matrix A is a number $\lambda$ which when subtracted from each diagonal entries of A, turns A into a singular matrix

i.e. det(B) = 0 where B = A - $\lambda$I

- If v is a non-zero vector and Av = $\lambda$v

then $\lambda$ is an *eigenvalue* of A and v is an **eigenvector** of A

In [48]:
eigenvalues, eigenvectors = np.linalg.eig(A)

In [49]:
eigenvalues

array([ 0.07179677, 13.92820323])